### ISSUE TITLE
Adding some lines to the new file

### ISSUE THREAD

**Issue by shiryz** [WebAhead/cli-intro#1]
The `new-file` that was created with `touch` is then `cat`ed to the terminal without adding any lines to it.
This is a good point to introduce `nano` or `echo` on how to print to file, though `echo` might be a bit complicated since we have to introduce `>>` as well.

@Karyum what do you think?

**Comment by Karyum** [comment]
What about if we just open up vscode from the terminal, write something in it. and cat it.
cause @jamiecoe i think introduced `nano` or `vim` (can't remember which) and till this day they never used it (wa4 that it)

**Comment by shiryz** [comment]
New order:

- Add `.` as the current directory, before `..` 
- `code` command should have a screenshot with `code new-file` (without `code .`)
- Add something to the file
- Move `cat` after adding something in vscode
- Screenshot for `code .`

**Comment by Karyum** [comment]
done
